# Generated by Django 2.1.3 on 2018-11-22 15:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20181122_1521'),
        ('authentication', '0002_auto_20181122_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Full name of kid', max_length=200)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Parent')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Kid')),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson')),
            ],
        ),
        migrations.AddField(
            model_name='registeredcourse',
            name='tracker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tracker'),
        ),
    ]
