# Generated by Django 2.1.3 on 2018-11-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20181122_1521'),
        ('main', '0002_auto_20181125_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.School'),
        ),
    ]
