# Generated by Django 2.1.3 on 2018-11-22 13:59

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=12, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField()),
                ('introductory_video', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseOwner',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=12, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=12, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.URLField()),
                ('video_link', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseOwner'),
        ),
    ]
