# Generated by Django 2.1.3 on 2018-11-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='introductory_video',
            field=models.URLField(help_text='Youtube link to the course intro'),
        ),
        migrations.AlterField(
            model_name='courseowner',
            name='password',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_link',
            field=models.URLField(help_text='Youtube link to the lesson'),
        ),
    ]
