# Generated by Django 2.1.3 on 2018-11-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181122_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseowner',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_number',
            field=models.IntegerField(default=0, help_text='Serial number of Lesson in course, must be unique.'),
            preserve_default=False,
        ),
    ]
