# Generated by Django 2.1.3 on 2018-12-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20181125_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=models.URLField(help_text='Link to pdf content'),
        ),
    ]
