# Generated by Django 2.1.3 on 2018-11-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='password',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='school',
            name='password',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
