# Generated by Django 2.1.3 on 2018-12-07 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181207_1625'),
        ('authentication', '0002_auto_20181122_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
